//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.23 at 12:21:19 AM CDT
//


package com.jolyjonesfamily.blurb.models;

import com.jolyjonesfamily.blurb.map.adapter.BlurbMapAdapter;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.Map;


/**
 * <p>Java class for blurb element declaration.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;element name="blurb">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}pattern"/>
 *           &lt;element ref="{}namespaces"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pattern",
    "namespaces"
})
@XmlRootElement(name = "blurb")
public class Blurb {

    @XmlElement(required = true)
    protected Cat pattern;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(BlurbMapAdapter.class)
    protected Map<String,Namespace> namespaces;

    /**
     * Gets the value of the pattern property.
     *
     * @return
     *     possible object is
     *     {@link Cat }
     *
     */
    public Cat getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     *
     * @param value
     *     allowed object is
     *     {@link Cat }
     *
     */
    public void setPattern(Cat value) {
        this.pattern = value;
    }

    /**
     * Sets the value of the namespaces property.
     *
     * @param value
     *     allowed object is
     *     {@link Namespaces }
     *
     */
    public void setNamespaces(Map<String, Namespace> value) {
        this.namespaces = value;
    }

    public Namespace getNamespace(String namespaceName) {
        return this.namespaces.get(namespaceName);
    }
}
